version: "3.8"

services:
  leaderboard-app:
    build: .
    container_name: leaderboard-app
    ports:
      - "3000:3000"
    depends_on:
      - leaderboard-db
    environment:
      # NODE_ENV: production
      DB_HOST: leaderboard-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: leaderBoardDB
    networks:
      - leaderboard-network

  leaderboard-db:
    image: postgres:17
    container_name: leaderboard-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: irroom04
      POSTGRES_DB: leaderBoardDB
    ports:
      - "5433:5432"
    networks:
      - leaderboard-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  leaderboard-network:

volumes:
  postgres_data: